[project]
name = "swe-agent-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.0.0",
    "mini-swe-agent>=1.3.0",
    "openai>=1.98.0",
    "openai-function-calling>=2.6.0",
]
